import { useParams, useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import remarkBreaks from 'remark-breaks';
import rehypeHighlight from 'rehype-highlight';
import rehypeRaw from 'rehype-raw';
import 'highlight.js/styles/github-dark.css';
import "./Report.css";
import "./ReportDetail.css";
// Import authored Markdown as raw text for precise rendering
// Vite supports ?raw imports; we'll declare types in src/types/raw.d.ts
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
import testMd from './test.md?raw';

interface ReportData {
  id: string;
  title: string;
  type: "development" | "infrastructure" | "community" | "business";
  status: "pending" | "in-progress" | "completed" | "rejected" | "ready to generate";
  priority: "low" | "medium" | "high" | "critical";
  location: string;
  submittedBy: string;
  submittedDate: string;
  description: string;
  tags: string[];
}

const ReportDetail = () => {
  const { reportId } = useParams<{ reportId: string }>();
  const navigate = useNavigate();
  const [isGenerating, setIsGenerating] = useState(true);
  const [generatedContent, setGeneratedContent] = useState<string>("");
  const [progress, setProgress] = useState(0);

  // Mock business report data (same as in Report component)
const reportData: ReportData[] = [
    {
        id: "BRP-001",
        title: "New Chagee Store Planning in Cyberjaya",
        type: "business",
        status: "completed",
        priority: "high",
        location: "Cyberjaya",
        submittedBy: "Chagee Malaysia",
        submittedDate: "2025-09-27",
        description: "Establishment of a new Chagee bubble tea outlet in Cyberjaya. This popular Taiwanese bubble tea brand will bring authentic flavors and high-quality beverages to Cyberjaya residents and visitors. The store will feature modern interior design, extensive menu options, and will contribute to the mall's dining and beverage ecosystem. Expected to create local employment opportunities and attract more foot traffic to the shopping center.",
        tags: ["food-and-beverage", "retail", "franchise", "taiwanese", "bubble-tea", "chagee", "commercial"]
    }
];

  const report = reportData.find(r => r.id === reportId);

  // Normalize markdown coming from API (which may contain escaped newlines like "\n")
  const normalizeMarkdown = (text: string) => {
    if (!text) return "";
    return text
      // Convert JSON-escaped newlines to real newlines
      .replace(/\\r\\n/g, "\n")
      .replace(/\\n/g, "\n")
      .replace(/\r\n/g, "\n")
      // Unwrap four-backtick markdown fences: ````markdown ... ```` -> inner content
      .replace(/````\s*markdown\s*\n([\s\S]*?)\n````/gi, (_m, p1) => p1)
      // Unwrap fenced HTML/SVG so they render as real elements (we use rehypeRaw)
      .replace(/```(?:html|svg)\s*\n([\s\S]*?)\n```/gi, (_m, p1) => p1)
      // Normalize multiple blank lines
      .replace(/\n{3,}/g, "\n\n")
      // Normalize list marker spacing ("*   " -> "* ", "1.  " -> "1. ")
  .replace(/^(\s*[-*])\s{2,}/gm, (_m, p1) => `${p1} `)
      .replace(/^(\s*\d+\.)\s{2,}/gm, (_m, p1) => `${p1} `)
      // Ensure a space after ATX headers like #Title -> # Title
      .replace(/(^|\n)(#{1,6})([^#\s])/g, (_m, p1, p2, p3) => `${p1}${p2} ${p3}`);
  };

  // Format API result for display
  const formatApiResult = (result: string) => {
    if (!result || result.trim() === '') {
      return generateDetailedReport();
    }
    
    // Clean the result text & normalize
    let cleanResult = normalizeMarkdown(result.trim());
    
    // If result is already formatted markdown, clean it up
    if (cleanResult.includes('#') || cleanResult.includes('**') || cleanResult.includes('*')) {
      // Ensure proper spacing between markdown elements
      cleanResult = cleanResult
        .replace(/([^\n])\n([#])/g, '$1\n\n$2'); // Add proper spacing before headers
      return cleanResult;
    }
    
    // If it's plain text, add proper markdown formatting
    return `# ${report?.title || 'Business Development Report'}

## Executive Summary

${cleanResult}

---

**Report Details:**
- **Location:** ${report?.location}
- **Submitted by:** ${report?.submittedBy}
- **Date:** ${new Date(report?.submittedDate || Date.now()).toLocaleDateString()}
- **Status:** ${report?.status}

---

*Report generated by AI Assistant on ${new Date().toLocaleDateString()}*`;
  };

  // API call to generate report
  const generateReportFromAPI = async () => {
    try {
      setIsGenerating(true);
      setProgress(0);
      
      const response = await fetch('https://7qb3nlxs-80.asse.devtunnels.ms/v1/workflows/run', {
        method: 'POST',
        headers: {
          'Authorization': 'Bearer app-hwfSl0fFkiawZhIT3PKEutjd',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          inputs: {
            title: report?.title || 'Business Report',
            location: report?.location || 'Cyberjaya',
            description: report?.description || 'Business development report'
          },
          response_mode: 'streaming',
          user: 'abc-123'
        })
      });

      if (!response.body) {
        throw new Error('No response body');
      }

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
  let accumulatedContent = '';

      while (true) {
        const { done, value } = await reader.read();
        
        if (done) {
          break;
        }

        const chunk = decoder.decode(value, { stream: true });
        const lines = chunk.split('\n');
        
        for (const line of lines) {
          if (line.startsWith('data: ')) {
            try {
              const data = JSON.parse(line.slice(6));
              console.log('Received event:', data.event, data);
              
              if (data.event === 'text_chunk' || data.event === 'agent_message') {
                if (data.data && data.data.text) {
                  accumulatedContent += data.data.text;
                  setGeneratedContent(normalizeMarkdown(accumulatedContent));
                  setProgress(prev => Math.min(prev + 5, 95));
                }
              }
              
              if (data.event === 'workflow_finished') {
                console.log('Workflow finished event:', data);
                
                // Extract the final result from the workflow_finished event
                if (data.data && data.data.outputs && data.data.outputs.result) {
                  const finalContent = formatApiResult(normalizeMarkdown(data.data.outputs.result));
                  setGeneratedContent(finalContent);
                  console.log('Using workflow result:', data.data.outputs.result);
                } else if (accumulatedContent) {
                  // Use accumulated content if no specific result in outputs
                  const formattedContent = formatApiResult(normalizeMarkdown(accumulatedContent));
                  setGeneratedContent(formattedContent);
                  console.log('Using accumulated content:', accumulatedContent);
                } else {
                  // Fallback to default content
                  setGeneratedContent(generateDetailedReport());
                  console.log('Using fallback content');
                }
                setIsGenerating(false);
                setProgress(100);
                break;
              }
            } catch {
              // Skip malformed JSON
              console.log('Skipping malformed JSON:', line);
            }
          }
        }
      }
    } catch (error) {
      console.error('Error generating report:', error);
      setIsGenerating(false);
      // Fallback to default content
      setGeneratedContent(generateDetailedReport());
    }
  };

  // Call API on component mount
  useEffect(() => {
    if (report) {
      generateReportFromAPI();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [reportId]);

  if (!report) {
    return (
      <div className="report-container">
        <div className="report-header">
          <div className="header-content">
            <button 
              className="back-button"
              onClick={() => navigate("/reports")}
              title="Back to Reports"
            >
              ← Back to Reports
            </button>
            <h1>Report Not Found</h1>
          </div>
        </div>
        <div className="no-reports">
          <div className="no-reports-icon">🔍</div>
          <h3>Report not found</h3>
          <p>The requested report could not be found.</p>
        </div>
      </div>
    );
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case "completed": return "#28a745";
      case "in-progress": return "#007bff";
      case "pending": return "#ffc107";
      case "rejected": return "#dc3545";
      default: return "#6c757d";
    }
  };

  const getPriorityColor = (priority: string) => {
    switch (priority) {
      case "critical": return "#dc3545";
      case "high": return "#fd7e14";
      case "medium": return "#ffc107";
      case "low": return "#28a745";
      default: return "#6c757d";
    }
  };

  const getTypeIcon = (type: string) => {
    switch (type) {
      case "development": return "🏗️";
      case "infrastructure": return "🛤️";
      case "community": return "👥";
      case "business": return "🏢";
      default: return "📄";
    }
  };

  // Generate detailed report content in markdown format
  const generateDetailedReport = () => {
    // Prefer the authored test.md if available
    const fileMd = typeof testMd === 'string' && testMd.trim().length > 0 ? normalizeMarkdown(testMd) : '';
    if (fileMd) return fileMd;
    return `# Marketing Research Report: Market Entry Strategy for Chagee in Cyberjaya

**Date:** September 27, 2025  
**Prepared For:** The Management and Expansion Team, Chagee  
**Prepared By:** Professional Business Analyst, CyberView Intelligence

---

## 1.0 Executive Summary

This report presents a comprehensive analysis of the market viability and strategic recommendations for the establishment of a new Chagee outlet in Cyberjaya. Our research, based on extensive demographic data, user-generated feedback, and geographical analysis, indicates an exceptionally strong and explicit market demand for Chagee's presence in this key technological hub.

### 1.1 Key Findings

- **Overwhelming Market Demand:** There is a significant, pre-existing, and vocal demand for a Chagee outlet in Cyberjaya. A user suggestion to open a Chagee at DPULZE Shopping Centre garnered **3,500 upvotes**, which is more than triple the support for the nearest competitor brand suggestion. This represents a rare and powerful market signal of guaranteed initial interest.

- **Ideal Target Demographic:** Cyberjaya's population is young, with a median age of 24.7 years. The largest population segments are aged 20-29, aligning perfectly with Chagee's core target market. Analysis of user support for Chagee reveals a highly concentrated customer profile: **70% are aged 20-30**, **66% are female**, and **69% are of Chinese ethnicity**.

- **Prime Location Identified:** **DPULZE Shopping Centre** has been identified as the optimal location for Chagee's inaugural outlet. It is a major commercial hub with high foot traffic, diverse entertainment options (including a cinema), and is the specific location requested by the vast majority of potential customers.

- **Favorable Competitive Landscape:** While other beverage brands like Tiger Sugar and KOI have some user support, the demand for Chagee is substantially higher. This indicates a significant opportunity for Chagee to enter the market as a leader and capture a dominant market share quickly.

### 1.2 Key Recommendations

1. **Immediate Site Acquisition:** Prioritize and aggressively pursue the acquisition of a high-visibility retail lease within **DPULZE Shopping Centre**. The ideal location would be on the ground floor or near the main entrance/cinema to maximize foot traffic and impulse purchases.

2. **Targeted Launch Marketing:** Develop a hyper-targeted digital marketing campaign focused on the identified customer segment (young, female, tech-savvy professionals and students). The campaign should leverage the "We Heard You" message, directly referencing the overwhelming online support to build an immediate connection with the community.

3. **Strategic Product Offering:** Launch with Chagee's full signature menu, with a special focus on the premium and fresh milk tea series that appeal to a discerning, health-conscious audience. Implement a grand opening promotion strategy to convert the high initial interest into strong sales.

4. **Phase Two Expansion Plan:** Following a successful launch at DPULZE, consider **Tamarind Square** as the location for a second outlet to capture a different segment of the Cyberjaya market. Monitor sales data and customer feedback to inform future expansion into smaller kiosk models near corporate campuses and universities.

This report concludes that Cyberjaya represents a high-potential, low-risk market for Chagee's expansion. The combination of a perfect demographic fit and explicit, quantifiable consumer demand creates a compelling business case for immediate market entry.

---

## 2.0 Company Background

**Chagee** is a prominent and rapidly growing modern tea beverage brand, renowned for its commitment to high-quality ingredients, authentic tea flavors, and a contemporary brand aesthetic. The company has successfully cultivated a loyal following by blending traditional tea culture with modern consumer preferences, focusing on fresh milk, premium tea leaves, and unique flavor profiles.

### 2.1 Objectives of this Report

The primary objective of this research is to assess the market feasibility of expanding Chagee's retail footprint into Cyberjaya. This report aims to:
- Analyze the demographic and psychographic profile of the Cyberjaya market.
- Identify and quantify consumer demand for Chagee and its competitors.
- Evaluate and recommend optimal locations for a new outlet.
- Provide actionable strategies for a successful market entry and sustainable growth.

The successful establishment of an outlet in Cyberjaya, a hub for technology, innovation, and a young, affluent population, would serve as a strategic milestone in Chagee's national expansion plan.

---

## 3.0 Market Analysis

The Cyberjaya market presents a unique and highly attractive opportunity for a premium beverage brand like Chagee. The area is characterized by a young, educated, and digitally-native population with significant disposable income.

### 3.1 Cyberjaya Demographic Profile

Cyberjaya's population dynamics are a strong indicator of market potential. The area has experienced rapid growth, which is projected to continue. The population is significantly younger than the national average, creating a vibrant consumer base.

| Demographic Metric | Value | Analysis & Implication for Chagee |
|:---|:---|:---|
| **Population (2015)** | 39,431 | A substantial existing customer base. |
| **Projected Population (2030)** | 48,365 | A growing market ensuring long-term sustainability and growth potential. |
| **Median Age** | **24.7 years** | **Extremely Favorable.** This indicates a market dominated by young adults, Chagee's primary target audience. |
| **Male Median Age** | 24.9 years | |
| **Female Median Age** | 24.5 years | |
| **Population Density** | 1,074 / km² | High density supports retail viability and concentrated marketing efforts. |

The most critical data point is the age distribution. The largest demographic cohorts are those aged **20-24 (5,600 individuals)** and **25-29 (5,374 individuals)**. Combined, these groups represent over a quarter of the entire population and are the primary consumers of premium lifestyle beverages.

### 3.2 Customer Segmentation and Profile

Analysis of user data from the provided platform allows for the creation of a precise primary customer persona for Chagee in Cyberjaya.

**Primary Target Persona: "The Cyberjaya Young Professional/Student"**

- **Age:** 20-30 years old (representing 70% of supporters).
- **Gender:** Female (representing 66% of supporters).
- **Ethnicity:** Chinese (representing 69% of supporters).
- **Psychographics:**
  - **Digitally Native:** Active on social platforms and community forums where they voice opinions and discover new brands.
  - **Socially Motivated:** Views beverage consumption as a social activity, often linked to outings with friends, family, or colleagues (e.g., after movies, during shopping).
  - **Brand and Quality Conscious:** Willing to pay a premium for high-quality ingredients, superior taste, and a strong brand identity. They are not just buying a drink; they are buying an experience.
  - **Community-Oriented:** Engages with local happenings and feels a sense of ownership when their feedback is acknowledged by brands.

### 3.3 Consumer Demand Analysis

The most compelling evidence for Chagee's expansion into Cyberjaya comes from direct user feedback. The volume and sentiment of this feedback indicate a market that is not just ready, but actively waiting for Chagee's arrival.

| Beverage Brand Suggestion | Location | User Upvotes |
|:---|:---|:---|
| **Chagee** | **DPULZE Shopping Centre** | **3,500** |
| Tiger Sugar | Tamarind Square | 1,000 |
| KOI | DPULZE Shopping Centre | 200 |
| Boba Guys | Tamarind Square | 100 |

**Analysis of User Comments for Chagee:**
- *"Love chagee! Always wanted to have Chagee in Cyberjaya."* - Indicates pre-existing brand awareness and pent-up demand.
- *"Chagee would be a perfect addition after a movie night!"* - Directly links the Chagee experience with a key activity at the proposed location (DPULZE has a cinema).
- *"My family would love this! Chagee has something for everyone."* - Broadens the appeal beyond young individuals to include family outings.
- *"It would be great to have more food options here. Chagee is a fantastic choice!"* - Positions Chagee as a desirable addition to the local food and beverage scene.

The data clearly demonstrates that Chagee is the undisputed market favorite among potential customers in Cyberjaya.

---

## 4.0 Location Analysis

The selection of the initial location is the most critical factor for a successful launch. The analysis points unequivocally to one primary location, with a viable secondary option for future expansion.

### 4.1 Evaluation of Potential Locations

Several types of locations were analyzed, including major commercial centers, residential areas, and undeveloped land plots. For an initial market entry, a location with high existing foot traffic and established commercial activity is paramount.

| Location Name | Type | Key Attributes | User Demand Signal | Suitability Score | Recommendation |
|:---|:---|:---|:---|:---|:---|
| **DPULZE Shopping Centre** | **Major Mall** | High foot traffic, cinema, diverse retail & dining, central hub. | **Extremely High (3,500 votes)** | **9.5/10** | **Primary Recommendation** |
| **Tamarind Square** | **Commercial Complex** | Popular dining/shopping hub, community focus, modern aesthetic. | High (1,000 votes for competitor) | **8.0/10** | **Secondary/Expansion** |
| **Near Serin/Kanvas SOHO** | **Residential Area** | High concentration of residents, potential for loyal customer base. | Low (indirect) | **6.0/10** | **Future Kiosk/Delivery Hub** |
| **Near Dell/Tech Hubs** | **Corporate Area** | Captive audience of working professionals, high weekday traffic. | Low (indirect) | **6.5/10** | **Future Kiosk/Targeted Delivery** |

### 4.2 Primary Recommended Location: DPULZE Shopping Centre

**Address:** DPULZE, Cyberjaya  
**Description:** DPULZE is one of Cyberjaya's largest and most established shopping malls. It serves as the primary commercial and entertainment destination for residents, students, and professionals in the area.

**Justification:**
- **Proven Demand:** The community has explicitly requested a Chagee at this exact location with 3,500 votes. This eliminates guesswork and significantly de-risks the investment.
- **Synergistic Tenant Mix:** The presence of a cinema, numerous restaurants, and retail outlets creates a perfect environment for Chagee. Customers are already in a "leisure and spend" mindset.
- **High Foot Traffic:** As a major mall, DPULZE guarantees consistent and high volumes of foot traffic throughout the week, with peaks during evenings and weekends.
- **Target Audience Concentration:** The mall is a popular hangout spot for the 20-30 age demographic that forms Chagee's core customer base.

---

## 5.0 Competitor Analysis

The competitive landscape in Cyberjaya for premium beverages exists but is not saturated. Chagee has a clear opportunity to position itself as the market leader due to its strong brand equity and specific product differentiation.

### 5.1 Direct Competitors

Based on user suggestions, the primary direct competitors are other modern tea and bubble tea brands.

- **Tiger Sugar:** Known for its brown sugar boba milk. It has a strong following (1,000 votes) but focuses on a more niche, indulgent product.
- **KOI:** A well-established bubble tea brand. Its lower vote count (200) suggests that while it is a known entity, it may not generate the same level of excitement as newer or more premium-focused brands in this market.
- **Boba Guys:** A craft bubble tea brand with minimal user support (100 votes), indicating low brand awareness in this specific market.

### 5.2 Competitive Positioning and Opportunities

Chagee is uniquely positioned to capitalize on several market gaps:

- **The Premium Tea Niche:** While competitors focus heavily on traditional bubble tea or brown sugar variants, Chagee can champion its use of high-quality, fresh ingredients and a wider variety of authentic tea-based drinks.
- **Brand Experience:** Chagee's modern, minimalist, and aesthetically pleasing store design will resonate strongly with the design-conscious demographic in Cyberjaya.
- **Market Leader by Demand:** Chagee can enter the market not as a challenger, but as the "people's choice." The overwhelming user support gives Chagee a significant first-mover advantage in terms of brand perception.

---

## 6.0 Recommendations

Based on the comprehensive analysis presented in this report, we propose the following actionable business strategies for a highly successful market entry into Cyberjaya.

### 6.1 Phase 1: Launch Strategy (0-6 Months)

1. **Location Acquisition (Immediate Priority):**
   - Engage with the leasing management of **DPULZE Shopping Centre** immediately.
   - Target a high-traffic location of approximately 800-1,200 sq. ft. on the ground or first floor, preferably near an entrance, escalator, or the cinema.
   - Negotiate lease terms to secure the location within the next 30-60 days.

2. **Marketing and Pre-Launch Campaign:**
   - **"Cyberjaya, We Heard You!":** Launch a digital marketing campaign on platforms popular with the target demographic (Instagram, TikTok, Facebook).
   - **Community Engagement:** Thank the 3,500+ users for their support and announce that Chagee is officially coming to DPULZE.
   - **Influencer Collaboration:** Partner with local Cyberjaya/Klang Valley food and lifestyle influencers to build hype before the opening.

3. **Grand Opening:**
   - Plan a major grand opening event.
   - Implement a "Buy One, Get One Free" or similar high-value promotion for the first 1-3 days to drive massive initial traffic.
   - Ensure the store is fully staffed and trained to handle high volume while maintaining excellent customer service and product quality.

### 6.2 Phase 2: Growth and Expansion (6-18 Months)

1. **Performance Monitoring:**
   - Closely monitor sales data, peak hours, and product mix performance at the DPULZE outlet.
   - Collect customer feedback through loyalty programs and in-store QR code surveys.

2. **Delivery and Online Ordering:**
   - Optimize presence on major food delivery platforms (GrabFood, Foodpanda) to capture the at-home and office delivery market.

3. **Second Outlet Evaluation:**
   - After 9-12 months of successful operation at DPULZE, begin formal evaluation and site scouting at **Tamarind Square**.

### 6.3 Long-Term Vision (18+ Months)

- **Kiosk Model Exploration:** Investigate the viability of smaller, lower-cost kiosk models to be placed within corporate office buildings, university campuses, or transport hubs.
- **Community Integration:** Solidify Chagee's position as a community brand by sponsoring local tech events, student activities, or wellness initiatives.

---

**Report Generated:** ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}  
**Report ID:** ${report?.id || 'BRP-001'}  
**System:** CyberView Business Intelligence Platform  

*This comprehensive market research report provides strategic insights for Chagee's expansion into the Cyberjaya market. For additional information or clarifications, please contact the CyberView Business Intelligence team.*`;
  };

  return (
    <div className="report-container">
      {/* Header */}
      <div className="report-header">
        <div className="header-content">
          <button 
            className="back-button"
            onClick={() => navigate("/reports")}
            title="Back to Reports"
          >
            ← Back to Reports
          </button>
          <div className="header-title">
            <h1>{getTypeIcon(report.type)} {report.title}</h1>
            <p>Detailed Business Development Report</p>
          </div>
        </div>
      </div>

      {/* Report Info */}
      <div className="report-detail-card">
        <div className="report-header-info">
          <div className="report-id-type">
            <span className="report-type-icon">{getTypeIcon(report.type)}</span>
            <span className="report-id">{report.id}</span>
          </div>
          <div className="report-badges">
            <span 
              className="status-badge"
              style={{ backgroundColor: getStatusColor(report.status) }}
            >
              {report.status.replace("-", " ").toUpperCase()}
            </span>
            <span 
              className="priority-badge"
              style={{ backgroundColor: getPriorityColor(report.priority) }}
            >
              {report.priority.toUpperCase()}
            </span>
          </div>
        </div>

        <div className="report-content">
          <div className="report-meta">
            <div className="meta-item">
              <span className="meta-icon">📍</span>
              <span>{report.location}</span>
            </div>
            <div className="meta-item">
              <span className="meta-icon">👤</span>
              <span>{report.submittedBy}</span>
            </div>
            <div className="meta-item">
              <span className="meta-icon">📅</span>
              <span>{new Date(report.submittedDate).toLocaleDateString()}</span>
            </div>
          </div>

          <div className="report-tags">
            {report.tags.map((tag, index) => (
              <span key={index} className="tag">
                {tag}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Detailed Report Content */}
      <div className="report-detail-content">
        {isGenerating ? (
          <div className="generating-container">
            <div className="generating-header">
              <h2>🤖 AI is Generating Your Report</h2>
              <p>Please wait while we create a comprehensive business report...</p>
            </div>
            
            <div className="progress-container">
              <div className="progress-bar">
                <div 
                  className="progress-fill" 
                  style={{ width: `${progress}%` }}
                ></div>
              </div>
              <span className="progress-text">{progress}% Complete</span>
            </div>

            <div className="generating-animation">
              <div className="dots">
                <span></span>
                <span></span>
                <span></span>
              </div>
            </div>

            {generatedContent && (
              <div className="preview-container">
                <h3>📄 Report Preview</h3>
                <div className="markdown-content preview">
                  <ReactMarkdown
                    // Treat single newlines as <br>, support GFM tables/lists, and raw HTML when present
                    remarkPlugins={[remarkGfm, remarkBreaks]}
                    rehypePlugins={[rehypeHighlight, rehypeRaw]}
                    components={{
                      h1: ({children}) => <h1 className="md-h1">{children}</h1>,
                      h2: ({children}) => <h2 className="md-h2">{children}</h2>,
                      h3: ({children}) => <h3 className="md-h3">{children}</h3>,
                      p: ({children}) => <p className="md-paragraph">{children}</p>,
                      ul: ({children}) => <ul className="md-list">{children}</ul>,
                      ol: ({children}) => <ol className="md-list">{children}</ol>,
                      li: ({children}) => <li className="md-list-item">{children}</li>,
                      blockquote: ({children}) => <blockquote className="md-blockquote">{children}</blockquote>,
                      table: ({children}) => <div className="md-table-container"><table className="md-table">{children}</table></div>,
                      th: ({children}) => <th className="md-th">{children}</th>,
                      td: ({children}) => <td className="md-td">{children}</td>,
                      code: ({children, className}) => {
                        const isInline = !className;
                        return isInline ? 
                          <code className="md-inline-code">{children}</code> : 
                          <pre className="md-code-block"><code className={className}>{children}</code></pre>
                      },
                      hr: () => <hr className="md-divider" />
                    }}
                  >
                    {normalizeMarkdown(generatedContent)}
                  </ReactMarkdown>
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className="markdown-content">
            <div className="report-completion-header">
              <h2>✅ Report Generated Successfully</h2>
              <p>Your comprehensive business development report is ready!</p>
            </div>
            
            <ReactMarkdown
              remarkPlugins={[remarkGfm, remarkBreaks]}
              rehypePlugins={[rehypeHighlight, rehypeRaw]}
              components={{
                h1: ({children}) => <h1 className="md-h1">{children}</h1>,
                h2: ({children}) => <h2 className="md-h2">{children}</h2>,
                h3: ({children}) => <h3 className="md-h3">{children}</h3>,
                p: ({children}) => <p className="md-paragraph">{children}</p>,
                ul: ({children}) => <ul className="md-list">{children}</ul>,
                ol: ({children}) => <ol className="md-list">{children}</ol>,
                li: ({children}) => <li className="md-list-item">{children}</li>,
                blockquote: ({children}) => <blockquote className="md-blockquote">{children}</blockquote>,
                table: ({children}) => <div className="md-table-container"><table className="md-table">{children}</table></div>,
                th: ({children}) => <th className="md-th">{children}</th>,
                td: ({children}) => <td className="md-td">{children}</td>,
                code: ({children, className}) => {
                  const isInline = !className;
                  return isInline ? 
                    <code className="md-inline-code">{children}</code> : 
                    <pre className="md-code-block"><code className={className}>{children}</code></pre>
                },
                hr: () => <hr className="md-divider" />
              }}
            >
              {normalizeMarkdown(generatedContent || generateDetailedReport())}
            </ReactMarkdown>
          </div>
        )}
      </div>
    </div>
  );
};

export default ReportDetail;